batch_size: 32
optimizer: adam
loss: cross_entropy
max_epoch: 1
exp_name: my_exp_1
num_workers: 0
seed: 1234
hidden_dim: orion~uniform(32,256,discrete=True)
num_classes: 10
architecture: simple_mlp
early_stopping:
  metric: val_loss
  mode: min
  patience: 3
