#!/bin/sh 

# exit at the first error
set -e

flake8 --ignore D --max-line-length=100 .  # Check everything but docstrings
flake8 --select D --ignore D104,D100,D401 --docstring-convention google --exclude tests/  # Check only the docstrings
