name: unit-tests
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
      - master
      - development
  pull_request:
    branches:
      - main
      - master
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: python-3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: linting checks
      run: |
        python -m pip install --upgrade pip
        pip install flake8 flake8-docstrings
        sh hooks/pre-commit
    - name: install project dependencies
      run: |
        pip install -e .
    -name: unit tests
      run: |
        pytest --cov=amlrt-project
    - name: pytorch-end2end
      run: |
        ./tests/end2end_pytorch/run.sh
    - name: doc-creation-test
      run: |
        ./tests/test_docs/run.sh
