name: unit-tests
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Set up Python
      run: uv python install 3.11

    - name: linting checks
      run: |
        uv venv
        uv pip install flake8 flake8-docstrings isort
        uv run sh hooks/pre-commit

    - name: Install the project
      run: uv sync --all-extras --dev

    - name: unit tests
      run: |
        uv run pytest --cov=amlrt-project
    - name: pytorch-end2end-single
      run: |
        uv run tests/end2end_pytorch/run_single.sh
    - name: pytorch-end2end-orion
      run: |
        uv run tests/end2end_pytorch/run_orion.sh
    - name: type checking
      run: |
        uv run pytype amlrt_project/
    - name: doc-creation-test
      run: |
        uv run tests/test_docs/run.sh
